#!/usr/bin/env python3
"""Clustering analysis for contact correlation matrices

This script performs clustering on correlation matrices generated by
ContactCorrelationAnalyzer to identify groups of correlated contacts.

Usage:
    python cluster_contact_correlation.py \
        --input output/allostery_analysis/1ao7_run1 \
        --method hierarchical \
        --threshold 0.7 \
        --output cluster_results
"""

import sys
from pathlib import Path
import argparse
import logging
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))

from immunex.analysis.allostery import ContactCorrelationAnalyzer

logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s:%(name)s:%(message)s'
)
logger = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(
        description='Cluster analysis for contact correlation matrix',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Hierarchical clustering
  python cluster_contact_correlation.py \\
      --input output/allostery_analysis/1ao7_run1 \\
      --method hierarchical \\
      --threshold 0.7 \\
      --output cluster_results_hierarchical

  # Network clustering (Louvain)
  python cluster_contact_correlation.py \\
      --input output/allostery_analysis/1ao7_run1 \\
      --method network \\
      --threshold 0.8 \\
      --network-method louvain \\
      --output cluster_results_network
        """
    )

    parser.add_argument(
        '--input', required=True,
        help='Input directory with correlation analysis results'
    )
    parser.add_argument(
        '--method', choices=['hierarchical', 'network'],
        default='hierarchical',
        help='Clustering method (default: hierarchical)'
    )
    parser.add_argument(
        '--threshold', type=float, default=0.7,
        help='Distance/correlation threshold for clustering (default: 0.7)'
    )
    parser.add_argument(
        '--min-cluster-size', type=int, default=3,
        help='Minimum cluster size (default: 3)'
    )
    parser.add_argument(
        '--output', default='./cluster_results',
        help='Output directory (default: ./cluster_results)'
    )
    parser.add_argument(
        '--linkage-method',
        choices=['single', 'complete', 'average', 'ward'],
        default='average',
        help='Linkage method for hierarchical clustering (default: average)'
    )
    parser.add_argument(
        '--network-method',
        choices=['louvain', 'greedy', 'label_prop'],
        default='louvain',
        help='Community detection method for network clustering (default: louvain)'
    )
    parser.add_argument(
        '--network-layout',
        choices=['spring', 'kamada'],
        default='spring',
        help='Network layout algorithm (default: spring)'
    )

    args = parser.parse_args()

    logger.info("=" * 60)
    logger.info("Contact Correlation Clustering Analysis")
    logger.info("=" * 60)

    try:
        # Load data
        input_path = Path(args.input)
        npz_file = input_path / "correlation_matrix.npz"
        labels_file = input_path / "contact_labels.csv"

        if not npz_file.exists():
            raise FileNotFoundError(f"Correlation matrix not found: {npz_file}")
        if not labels_file.exists():
            raise FileNotFoundError(f"Contact labels not found: {labels_file}")

        logger.info(f"Loading correlation data from {args.input}")

        # Load correlation matrix
        data = np.load(npz_file)
        correlation_matrix = data['correlation_matrix']

        # Load contact labels
        labels_df = pd.read_csv(labels_file)
        contact_labels = list(labels_df[['ResA_ID', 'ResA_Name', 'ResB_ID', 'ResB_Name']].itertuples(index=False, name=None))

        logger.info(f"Loaded correlation matrix: {correlation_matrix.shape}")
        logger.info(f"Loaded {len(contact_labels)} contact labels")

        # Create temporary analyzer instance (just for clustering methods)
        analyzer = ContactCorrelationAnalyzer.__new__(ContactCorrelationAnalyzer)
        analyzer.correlation_matrix = correlation_matrix

        # Perform clustering
        if args.method == 'hierarchical':
            logger.info("\nRunning hierarchical clustering...")
            results = analyzer.cluster_hierarchical(
                correlation_matrix=correlation_matrix,
                method=args.linkage_method,
                threshold=args.threshold,
                min_cluster_size=args.min_cluster_size
            )

            # Visualize
            analyzer.plot_cluster_dendrogram(
                linkage_matrix=results['linkage_matrix'],
                output_file=f"{args.output}/cluster_dendrogram.png",
                threshold=args.threshold
            )
        else:
            logger.info("\nRunning network clustering...")
            results = analyzer.cluster_network(
                correlation_matrix=correlation_matrix,
                threshold=args.threshold,
                min_cluster_size=args.min_cluster_size,
                method=args.network_method
            )

            # Visualize
            analyzer.plot_cluster_network(
                graph=results['graph'],
                cluster_labels=results['cluster_labels'],
                output_file=f"{args.output}/cluster_network.png",
                layout=args.network_layout
            )

        # Save results
        logger.info("\nSaving results...")
        saved_files = analyzer.save_cluster_results(
            cluster_labels=results['cluster_labels'],
            contact_labels=contact_labels,
            correlation_matrix=correlation_matrix,
            output_dir=args.output
        )

        # Print summary
        logger.info("\n" + "=" * 60)
        logger.info("CLUSTERING RESULTS")
        logger.info("=" * 60)
        logger.info(f"Method: {args.method}")
        logger.info(f"Total contacts: {correlation_matrix.shape[0]}")
        logger.info(f"Identified clusters: {results['n_clusters']}")
        logger.info(f"Noise contacts: {np.sum(results['cluster_labels'] < 0)}")

        if args.method == 'network' and 'modularity' in results:
            logger.info(f"Network modularity: {results['modularity']:.3f}")

        logger.info("\nOutput files:")
        logger.info(f"  - {args.output}/cluster_assignments.csv")
        logger.info(f"  - {args.output}/cluster_summary.csv")
        if args.method == 'hierarchical':
            logger.info(f"  - {args.output}/cluster_dendrogram.png")
        else:
            logger.info(f"  - {args.output}/cluster_network.png")

        logger.info("\nClustering analysis completed successfully!")
        logger.info("=" * 60)

    except Exception as e:
        logger.error(f"Error during clustering analysis: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
