#!/usr/bin/env python3
"""Generate PyMOL visualization script for clustering results

This script:
1. Extracts a single protein frame from trajectory as PDB
2. Generates PyMOL script to visualize clusters on structure
"""

import sys
from pathlib import Path
import argparse
import logging
import numpy as np
import pandas as pd
import MDAnalysis as mda

sys.path.insert(0, str(Path(__file__).parent.parent))

logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s:%(name)s:%(message)s'
)
logger = logging.getLogger(__name__)


def extract_protein_pdb(topology, trajectory, output_pdb, frame_index=0):
    """Extract a single protein frame from trajectory as PDB

    Args:
        topology: Path to topology file (TPR)
        trajectory: Path to trajectory file (XTC)
        output_pdb: Output PDB file path
        frame_index: Frame to extract (default: 0, first frame)
    """
    logger.info(f"Loading trajectory: {trajectory}")
    u = mda.Universe(str(topology), str(trajectory))

    # Select protein atoms only
    protein = u.select_atoms("protein")
    logger.info(f"Selected {len(protein)} protein atoms")

    # Move to specified frame
    u.trajectory[frame_index]
    logger.info(f"Extracting frame {frame_index} (time: {u.trajectory.time:.2f} ps)")

    # Write PDB
    protein.write(str(output_pdb))
    logger.info(f"Protein structure saved: {output_pdb}")

    return str(output_pdb)


def generate_pymol_script(
    cluster_assignments_csv,
    pdb_file,
    output_script,
    topology=None,
    top_n_clusters=15,
    min_cluster_size=5
):
    """Generate PyMOL script to visualize clusters

    Args:
        cluster_assignments_csv: CSV file with cluster assignments
        pdb_file: PDB structure file
        output_script: Output PyMOL script (.pml)
        topology: Topology file (TPR) for chain information
        top_n_clusters: Number of largest clusters to visualize
        min_cluster_size: Minimum cluster size to include
    """
    logger.info(f"Reading cluster assignments: {cluster_assignments_csv}")
    df = pd.read_csv(cluster_assignments_csv)

    # Filter valid clusters
    clustered = df[df['Cluster'] >= 0]
    logger.info(f"Total contacts: {len(df)}, Clustered: {len(clustered)}, Noise: {len(df) - len(clustered)}")

    # Build residue ID to chain ID mapping from topology
    resid_to_chain = {}
    if topology:
        logger.info(f"Loading topology to get chain information: {topology}")
        u = mda.Universe(str(topology))
        protein = u.select_atoms("protein")
        for res in protein.residues:
            resid = res.resid
            segid = res.segment.segid
            # Extract chain from segid (format: seg_0_Protein_chain_A)
            if "chain_" in segid:
                chain = segid.split("chain_")[-1]
                resid_to_chain[resid] = chain
        logger.info(f"Built residue-to-chain mapping: {len(resid_to_chain)} residues")

    # Get cluster residues with chain information
    cluster_residues = {}
    for cluster_id in sorted(clustered['Cluster'].unique()):
        cluster_data = clustered[clustered['Cluster'] == cluster_id]
        residues = {}  # {chain: set(resids)}

        for _, row in cluster_data.iterrows():
            res_a_id = int(row['ResA_ID'])
            res_b_id = int(row['ResB_ID'])

            # Get chain for each residue
            chain_a = resid_to_chain.get(res_a_id, 'A')  # Default to 'A' if not found
            chain_b = resid_to_chain.get(res_b_id, 'A')

            if chain_a not in residues:
                residues[chain_a] = set()
            if chain_b not in residues:
                residues[chain_b] = set()

            residues[chain_a].add(res_a_id)
            residues[chain_b].add(res_b_id)

        # Convert sets to sorted lists
        cluster_residues[cluster_id] = {chain: sorted(resids) for chain, resids in residues.items()}

    # Sort clusters by size (total number of unique residues across all chains)
    cluster_sizes = []
    for cid, chains_dict in cluster_residues.items():
        total_residues = sum(len(resids) for resids in chains_dict.values())
        cluster_sizes.append((cid, total_residues))
    cluster_sizes.sort(key=lambda x: x[1], reverse=True)

    # Filter by size and select top N
    cluster_sizes = [(cid, size) for cid, size in cluster_sizes if size >= min_cluster_size]
    cluster_sizes = cluster_sizes[:top_n_clusters]

    logger.info(f"Visualizing top {len(cluster_sizes)} clusters (min size: {min_cluster_size})")

    # Generate PyMOL script
    script_lines = []
    script_lines.append("# PyMOL script for cluster visualization")
    script_lines.append("# Generated by Immunex clustering analysis\n")

    # Load structure
    script_lines.append(f"load {Path(pdb_file).name}\n")

    # Basic settings
    script_lines.append("# Basic visualization settings")
    script_lines.append("bg_color white")
    script_lines.append("set cartoon_fancy_helices, 1")
    script_lines.append("set cartoon_side_chain_helper, 1")
    script_lines.append("hide everything")
    script_lines.append("show cartoon")
    script_lines.append("color gray90, all\n")

    # Define color palette (colorblind-friendly)
    colors = [
        "red", "blue", "green", "yellow", "orange",
        "purple", "cyan", "magenta", "salmon", "lightblue",
        "palegreen", "wheat", "violet", "deepsalmon", "marine"
    ]

    # Create cluster objects and color them
    script_lines.append("# Cluster objects and coloring")
    for idx, (cluster_id, size) in enumerate(cluster_sizes):
        chains_dict = cluster_residues[cluster_id]
        color = colors[idx % len(colors)]

        script_lines.append(f"# Cluster {cluster_id}: {size} residues")

        # Build selection string with chain information
        selection_parts = []
        for chain, resids in sorted(chains_dict.items()):
            residue_str = "+".join(map(str, resids))
            selection_parts.append(f"(chain {chain} and resi {residue_str})")

        selection_string = " or ".join(selection_parts)

        # Create object instead of selection
        script_lines.append(f"create cluster_{cluster_id}, {selection_string}")
        script_lines.append(f"color {color}, cluster_{cluster_id}")
        script_lines.append(f"disable cluster_{cluster_id}")  # Start with disabled
        script_lines.append("")

    # View settings
    script_lines.append("# View settings")
    script_lines.append("orient")
    script_lines.append("zoom all, 5")
    script_lines.append("set ray_shadows, 0")
    script_lines.append("set antialias, 2")
    script_lines.append("set orthoscopic, 1\n")

    # Legend (as comment)
    script_lines.append("# Cluster legend:")
    for idx, (cluster_id, size) in enumerate(cluster_sizes):
        color = colors[idx % len(colors)]
        script_lines.append(f"#   Cluster {cluster_id}: {size} residues ({color})")

    # Write script
    with open(output_script, 'w') as f:
        f.write('\n'.join(script_lines))

    logger.info(f"PyMOL script saved: {output_script}")

    # Generate usage instructions
    instructions = f"""
PyMOL Visualization Instructions:
=================================

1. Open PyMOL and run:
   File > Run Script > {Path(output_script).name}

2. Or from command line:
   pymol {Path(output_script).name}

3. Interactive controls:
   - Rotate: Left mouse drag
   - Zoom: Scroll wheel
   - Pan: Right mouse drag
   - Toggle cluster visibility: Click cluster_N in object panel

4. Export high-resolution image:
   ray 2400, 2400
   png cluster_visualization.png, dpi=300

Cluster Summary:
"""
    for idx, (cluster_id, size) in enumerate(cluster_sizes):
        color = colors[idx % len(colors)]
        instructions += f"  Cluster {cluster_id}: {size} residues ({color})\n"

    instructions_file = Path(output_script).with_suffix('.txt')
    with open(instructions_file, 'w') as f:
        f.write(instructions)

    logger.info(f"Usage instructions saved: {instructions_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate PyMOL visualization for clustering results',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        '--topology', required=True,
        help='Topology file (TPR)'
    )
    parser.add_argument(
        '--trajectory', required=True,
        help='Trajectory file (XTC)'
    )
    parser.add_argument(
        '--cluster-csv', required=True,
        help='Cluster assignments CSV file'
    )
    parser.add_argument(
        '--output-dir', default='./pymol_visualization',
        help='Output directory (default: ./pymol_visualization)'
    )
    parser.add_argument(
        '--frame', type=int, default=0,
        help='Frame index to extract (default: 0)'
    )
    parser.add_argument(
        '--top-n-clusters', type=int, default=15,
        help='Number of top clusters to visualize (default: 15)'
    )
    parser.add_argument(
        '--min-cluster-size', type=int, default=5,
        help='Minimum cluster size (default: 5)'
    )

    args = parser.parse_args()

    # Create output directory
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("=" * 60)
    logger.info("PyMOL Cluster Visualization Generator")
    logger.info("=" * 60)

    # Extract PDB
    pdb_file = output_dir / "protein_structure.pdb"
    extract_protein_pdb(
        topology=args.topology,
        trajectory=args.trajectory,
        output_pdb=pdb_file,
        frame_index=args.frame
    )

    # Generate PyMOL script
    pymol_script = output_dir / "cluster_visualization.pml"
    generate_pymol_script(
        cluster_assignments_csv=args.cluster_csv,
        pdb_file=pdb_file,
        output_script=pymol_script,
        topology=args.topology,
        top_n_clusters=args.top_n_clusters,
        min_cluster_size=args.min_cluster_size
    )

    logger.info("\n" + "=" * 60)
    logger.info("SUCCESS")
    logger.info("=" * 60)
    logger.info(f"Output directory: {output_dir}")
    logger.info(f"  - protein_structure.pdb")
    logger.info(f"  - cluster_visualization.pml")
    logger.info(f"  - cluster_visualization.txt (instructions)")
    logger.info("\nTo visualize:")
    logger.info(f"  cd {output_dir}")
    logger.info(f"  pymol cluster_visualization.pml")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
