#!/usr/bin/env python3
"""
Example usage of TCR-pMHC docking angle analysis.

This script demonstrates how to:
1. Calculate docking angles for a single structure
2. Calculate docking angles for an MD trajectory
3. Customize atom selections for different systems
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from aftermd.analysis.angles import DockingAngleAnalyzer


def example_single_structure():
    """
    Example 1: Calculate docking angles for a single structure.
    """
    print("=" * 70)
    print("Example 1: Single Structure Analysis")
    print("=" * 70)

    topology = "path/to/structure.pdb"

    selections = {
        'mhc': "chainID A and resid 50:86 140:176 and name CA",
        'tcr_alpha_cys': "chainID D and resid 22 92 and name CA",
        'tcr_beta_cys': "chainID E and resid 23 89 and name CA",
        'tcr_v': "chainID D E and resid 1:115 and name CA",
        'peptide': "chainID C and name CA"
    }

    print("\nInitializing analyzer...")
    print(f"  Topology: {topology}")

    print("\nSelections:")
    for key, sel in selections.items():
        print(f"  {key:20s}: {sel}")

    print("\nNote: This is a template example.")
    print("      Replace with actual file paths and selections for your system.")
    print()


def example_trajectory_analysis():
    """
    Example 2: Calculate docking angles for MD trajectory.
    """
    print("=" * 70)
    print("Example 2: MD Trajectory Analysis")
    print("=" * 70)

    topology = "path/to/md.tpr"
    trajectory = "path/to/md_pbc.xtc"

    selections = {
        'mhc': "chainID A and resid 50:86 140:176 and name CA",
        'tcr_alpha_cys': "chainID D and resid 22 92 and name CA",
        'tcr_beta_cys': "chainID E and resid 23 89 and name CA",
        'tcr_v': "chainID D E and resid 1:115 and name CA",
        'peptide': "chainID C and name CA"
    }

    print("\nInitializing analyzer...")
    print(f"  Topology: {topology}")
    print(f"  Trajectory: {trajectory}")

    print("\nCalculating docking angles...")
    print("  This would calculate angles for each frame")
    print("  Output: times, twist, tilt, swing arrays")

    print("\nSaving results...")
    print("  CSV format: docking_angles.csv")
    print("  XVG format: docking_angles.xvg")

    print("\nStatistical summary:")
    print("  Twist: mean ± std degrees")
    print("  Tilt: mean ± std degrees")
    print("  Swing: mean ± std degrees")
    print()


def example_custom_selections():
    """
    Example 3: Custom selections for different systems.
    """
    print("=" * 70)
    print("Example 3: Custom Selection Strategies")
    print("=" * 70)

    print("\nClass I MHC (HLA-A, HLA-B, HLA-C):")
    print("  mhc_selection = 'chainID A and resid 50:86 140:176 and name CA'")
    print("  # Alpha1 (50-86) and Alpha2 (140-176) helices")

    print("\nClass II MHC (HLA-DR, HLA-DQ, HLA-DP):")
    print("  mhc_selection = 'chainID A B and resid 50:86 and name CA'")
    print("  # Alpha1 and Beta1 domains")

    print("\nTCR V domain selection strategies:")

    print("\n  Strategy 1: Entire V domains")
    print("  tcr_v_selection = 'chainID D E and resid 1:115 and name CA'")

    print("\n  Strategy 2: Exclude CDR loops")
    print("  tcr_v_selection = 'chainID D E and (resid 1:25 35:45 60:70 90:115) and name CA'")

    print("\n  Strategy 3: Framework regions only")
    print("  tcr_v_selection = 'chainID D E and (resid 1-30 40-50 70-90 100-115) and name CA'")

    print("\nDisulfide bond selections (conserved cysteines):")
    print("  V_alpha: 'chainID D and resid 22 92 and name CA'")
    print("  V_beta: 'chainID E and resid 23 89 and name CA'")
    print("  Note: Adjust residue numbers based on your numbering scheme")

    print("\nPeptide selection:")
    print("  peptide_selection = 'chainID C and name CA'")
    print("  # Typically 8-15 residues for Class I, longer for Class II")
    print()


def example_output_formats():
    """
    Example 4: Output file formats and analysis.
    """
    print("=" * 70)
    print("Example 4: Output Formats")
    print("=" * 70)

    print("\nCSV Output Format (docking_angles.csv):")
    print("-" * 50)
    print("Time_ps,Twist_deg,Tilt_deg,Swing_deg")
    print("0.000,45.23,32.15,10.45")
    print("10.000,46.12,31.98,-8.23")
    print("20.000,44.87,33.21,12.34")
    print("...")

    print("\nXVG Output Format (GROMACS compatible):")
    print("-" * 50)
    print("# TCR-pMHC Docking Angles")
    print("# Generated by AfterMD DockingAngleAnalyzer")
    print("@ title \"Docking Angles vs Time\"")
    print("@ xaxis  label \"Time (ps)\"")
    print("@ yaxis  label \"Angle (degrees)\"")
    print("@ TYPE xy")
    print("@ s0 legend \"Twist\"")
    print("@ s1 legend \"Tilt\"")
    print("@ s2 legend \"Swing\"")
    print("    0.000   45.230   32.150   10.450")
    print("   10.000   46.120   31.980   -8.230")
    print("...")

    print("\nSubsequent Analysis:")
    print("  - Load CSV with pandas: df = pd.read_csv('docking_angles.csv')")
    print("  - Plot with matplotlib or PlotManager")
    print("  - Calculate statistics: mean, std, distribution")
    print("  - Identify conformational clusters")
    print()


def print_usage_code():
    """
    Example 5: Actual Python code for usage.
    """
    print("=" * 70)
    print("Example 5: Python Code Template")
    print("=" * 70)

    code = '''
# Import the analyzer
from aftermd.analysis.angles import DockingAngleAnalyzer

# Initialize with your files
analyzer = DockingAngleAnalyzer(
    topology="md.tpr",
    trajectory="md_pbc.xtc"
)

# Define selections for your system
selections = {
    'mhc': "chainID A and resid 50:86 140:176 and name CA",
    'tcr_alpha_cys': "chainID D and resid 22 92 and name CA",
    'tcr_beta_cys': "chainID E and resid 23 89 and name CA",
    'tcr_v': "chainID D E and resid 1:115 and name CA",
    'peptide': "chainID C and name CA"
}

# Calculate for entire trajectory
times, twist, tilt, swing = analyzer.calculate_docking_angles_trajectory(
    mhc_selection=selections['mhc'],
    tcr_alpha_cys_selection=selections['tcr_alpha_cys'],
    tcr_beta_cys_selection=selections['tcr_beta_cys'],
    tcr_v_selection=selections['tcr_v'],
    peptide_selection=selections['peptide'],
    stride=10,  # Analyze every 10th frame
    output_file="docking_angles.csv"
)

# Print statistics
import numpy as np
print(f"Twist: {np.mean(twist):.2f} ± {np.std(twist):.2f} degrees")
print(f"Tilt: {np.mean(tilt):.2f} ± {np.std(tilt):.2f} degrees")
print(f"Swing: {np.mean(swing):.2f} ± {np.std(swing):.2f} degrees")
'''

    print(code)


def main():
    """Run all examples."""
    example_single_structure()
    example_trajectory_analysis()
    example_custom_selections()
    example_output_formats()
    print_usage_code()

    print("=" * 70)
    print("For more information, see:")
    print("  - docs/ANGLE_MODULE_REDESIGN.md")
    print("  - aftermd/analysis/angles/__init__.py")
    print("=" * 70)


if __name__ == "__main__":
    main()
