#!/usr/bin/env python3
"""
Generate a PyMOL script to visualize all CDR loops plus contact-enriched loops.

This script consumes Immunex contact outputs and produces a human-oriented
.pml session script with:
- peptide / HLA / TCR base coloring
- all CDR loops colored for structural verification
- contacted CDR loops highlighted with sticks
- contact partner residues shown as sticks
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, List, Tuple


CDR_LOOP_COLORS = {
    "CDR1_alpha": "marine",
    "CDR2_alpha": "blue",
    "CDR3_alpha": "deepblue",
    "CDR1_beta": "lightorange",
    "CDR2_beta": "orange",
    "CDR3_beta": "red",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--structure", required=True, help="Structure file to load in PyMOL")
    parser.add_argument("--contact-report", required=True, help="Human-readable contact report CSV")
    parser.add_argument("--cdr-metadata", required=True, help="CDR metadata JSON generated by Immunex")
    parser.add_argument("--output", required=True, help="Output .pml file")
    parser.add_argument(
        "--interaction-class",
        default="peptide_tcr",
        choices=["peptide_tcr", "hla_tcr", "beta2m_tcr", "all"],
        help="Which contact class to visualize",
    )
    parser.add_argument(
        "--min-frequency",
        type=float,
        default=0.05,
        help="Minimum contact frequency for retaining loops and partner residues",
    )
    parser.add_argument(
        "--include-framework",
        action="store_true",
        help="Also highlight framework-only TCR residues",
    )
    parser.add_argument(
        "--hide-noncontact-cdr-sticks",
        action="store_true",
        help="Show non-contact CDR loops as cartoon only",
    )
    parser.add_argument(
        "--top-contact-labels",
        type=int,
        default=8,
        help="Number of top contact residue pairs to label",
    )
    return parser.parse_args()


def load_contact_rows(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def load_cdr_metadata(path: Path) -> Dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def filter_rows(
    rows: List[Dict[str, str]],
    interaction_class: str,
    min_frequency: float,
    include_framework: bool,
) -> List[Dict[str, str]]:
    filtered = []
    for row in rows:
        if interaction_class != "all" and row["interaction_class"] != interaction_class:
            continue
        if float(row["contact_frequency"]) < min_frequency:
            continue
        if not include_framework and row["tcr_region"] == "framework":
            continue
        filtered.append(row)
    return filtered


def collect_selected_loops(rows: List[Dict[str, str]]) -> List[str]:
    loops = {
        row["tcr_region_detailed"]
        for row in rows
        if row["tcr_region_detailed"] and row["tcr_region_detailed"] != "framework"
    }
    return sorted(loops)


def collect_all_loops(cdr_metadata: Dict) -> List[str]:
    loops: List[str] = []
    for suffix in ("alpha", "beta"):
        for cdr_number in (1, 2, 3):
            loop_name = f"CDR{cdr_number}_{suffix}"
            loop_map = build_loop_selection_map(cdr_metadata, [loop_name])
            if loop_name in loop_map:
                loops.append(loop_name)
    return loops


def build_loop_selection_map(cdr_metadata: Dict, selected_loops: List[str]) -> Dict[str, Tuple[str, int, int]]:
    loop_map: Dict[str, Tuple[str, int, int]] = {}
    chains = cdr_metadata.get("chains", {})
    for loop_name in selected_loops:
        region_name, suffix = loop_name.split("_", 1)
        chain_name = f"TCR_{suffix}"
        chain_info = chains.get(chain_name, {})
        chain_id = chain_info.get("chain_id")
        if not chain_id:
            selection = chain_info.get("selection", "")
            if isinstance(selection, str) and selection.startswith("chainID "):
                chain_id = selection.split(" ", 1)[1].strip()
        cdr_number = int(region_name.replace("CDR", ""))
        cdr_info = None
        nested_cdrs = chain_info.get("cdrs")
        if isinstance(nested_cdrs, dict):
            cdr_info = nested_cdrs.get(cdr_number) or nested_cdrs.get(str(cdr_number))
        if cdr_info is None:
            cdr_info = chain_info.get(f"cdr{cdr_number}")
        if not chain_id or not cdr_info:
            continue
        start, end = cdr_info["residue_range"]
        loop_map[loop_name] = (chain_id, int(start), int(end))
    return loop_map


def collect_partner_residues(rows: List[Dict[str, str]]) -> List[Tuple[str, int]]:
    partners = {(row["phla_chain_id"], int(row["phla_resid"])) for row in rows}
    return sorted(partners, key=lambda item: (item[0], item[1]))


def collect_top_contact_pairs(rows: List[Dict[str, str]], top_n: int) -> List[Dict[str, str]]:
    def sort_key(row: Dict[str, str]):
        return (
            -float(row["contact_frequency"]),
            -int(row["contact_frames"]),
            float(row["min_distance_angstrom"]),
        )

    sorted_rows = sorted(rows, key=sort_key)
    seen = set()
    top_pairs = []
    for row in sorted_rows:
        key = (
            row["phla_chain_id"],
            row["phla_resid"],
            row["tcr_chain_id"],
            row["tcr_resid"],
        )
        if key in seen:
            continue
        seen.add(key)
        top_pairs.append(row)
        if len(top_pairs) >= top_n:
            break
    return top_pairs


def build_pml(
    structure_path: Path,
    all_loops: List[str],
    selected_loops: List[str],
    loop_selection_map: Dict[str, Tuple[str, int, int]],
    partner_residues: List[Tuple[str, int]],
    top_contact_pairs: List[Dict[str, str]],
    hide_noncontact_cdr_sticks: bool = False,
) -> str:
    lines = [
        "reinitialize",
        f"load {structure_path.as_posix()}, complex",
        "hide everything, all",
        "show cartoon, polymer.protein",
        "bg_color white",
        "set ray_opaque_background, off",
        "color grey80, chain A",
        "color grey60, chain B",
        "color yellow, chain C",
        "color palecyan, chain D",
        "color lightpink, chain E",
        "show sticks, chain C",
        "set stick_radius, 0.18",
        "set cartoon_transparency, 0.35",
        "set label_size, 18",
        "set label_color, black",
        "set dash_gap, 0.2",
        "set dash_radius, 0.12",
        "util.cnc",
    ]

    for loop_name in all_loops:
        if loop_name not in loop_selection_map:
            continue
        chain_id, start, end = loop_selection_map[loop_name]
        color = CDR_LOOP_COLORS.get(loop_name, "magenta")
        selection_name = loop_name.lower()
        lines.extend(
            [
                f"select {selection_name}, chain {chain_id} and resi {start}-{end}",
                f"show cartoon, {selection_name}",
                f"color {color}, {selection_name}",
            ]
        )
        if not hide_noncontact_cdr_sticks:
            lines.append(f"hide sticks, {selection_name}")

    for loop_name in selected_loops:
        if loop_name not in loop_selection_map:
            continue
        selection_name = loop_name.lower()
        lines.extend(
            [
                f"show sticks, {selection_name}",
                f"set cartoon_transparency, 0.0, {selection_name}",
                f"set stick_radius, 0.24, {selection_name}",
            ]
        )

    if partner_residues:
        partner_terms = [f"(chain {chain_id} and resi {resid})" for chain_id, resid in partner_residues]
        partner_expr = " or ".join(partner_terms)
        lines.extend(
            [
                f"select contact_partners, {partner_expr}",
                "show sticks, contact_partners",
                "color tv_yellow, contact_partners",
            ]
        )

    for idx, row in enumerate(top_contact_pairs, start=1):
        phla_sel = f"top_phla_{idx}"
        tcr_sel = f"top_tcr_{idx}"
        dash_name = f"top_contact_{idx}"
        phla_label = f"{row['phla_region']} {row['phla_residue']}"
        tcr_label = f"{row['tcr_chain']} {row['tcr_residue']} {row['tcr_region']}"
        lines.extend(
            [
                f"select {phla_sel}, chain {row['phla_chain_id']} and resi {row['phla_resid']} and name CA",
                f"select {tcr_sel}, chain {row['tcr_chain_id']} and resi {row['tcr_resid']} and name CA",
                f"show spheres, {phla_sel} or {tcr_sel}",
                f"set sphere_scale, 0.30, {phla_sel} or {tcr_sel}",
                f"label {phla_sel}, \"{phla_label}\"",
                f"label {tcr_sel}, \"{tcr_label}\"",
                f"distance {dash_name}, {phla_sel}, {tcr_sel}",
                f"hide labels, {dash_name}",
            ]
        )

    lines.extend(
        [
            "zoom polymer.protein",
            "orient polymer.protein",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    structure_path = Path(args.structure).resolve()
    contact_report_path = Path(args.contact_report).resolve()
    cdr_metadata_path = Path(args.cdr_metadata).resolve()
    output_path = Path(args.output).resolve()

    rows = load_contact_rows(contact_report_path)
    filtered_rows = filter_rows(
        rows=rows,
        interaction_class=args.interaction_class,
        min_frequency=args.min_frequency,
        include_framework=args.include_framework,
    )
    selected_loops = collect_selected_loops(filtered_rows)
    cdr_metadata = load_cdr_metadata(cdr_metadata_path)
    all_loops = collect_all_loops(cdr_metadata)
    loop_selection_map = build_loop_selection_map(cdr_metadata, all_loops)
    partner_residues = collect_partner_residues(filtered_rows)
    top_contact_pairs = collect_top_contact_pairs(filtered_rows, args.top_contact_labels)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        build_pml(
            structure_path=structure_path,
            all_loops=all_loops,
            selected_loops=selected_loops,
            loop_selection_map=loop_selection_map,
            partner_residues=partner_residues,
            top_contact_pairs=top_contact_pairs,
            hide_noncontact_cdr_sticks=args.hide_noncontact_cdr_sticks,
        ),
        encoding="utf-8",
    )

    print(f"Wrote PyMOL script: {output_path}")
    print(f"All loops: {all_loops}")
    print(f"Selected loops: {selected_loops}")
    print(f"Partner residues: {len(partner_residues)}")
    print(f"Top labeled pairs: {len(top_contact_pairs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
